### PR TITLE
Fix the error on some empty option value of post directive

### LINKED ISSUE #154: Exception occurred on some empty option value of post directive
### Describe the bug

Same as the issue title.

### To Reproduce

Prepare the rst file containing some empty options of the post directive, like generated by `ablog post`.

```rst
1
=

.. post:: Aug 11, 2022
   :tags:
   :category:
```

Build it with `ablog build`.

### What happened?

```zsh
% ablog build              
Running Sphinx v5.1.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [dirhtml]: targets for 4 source files that are out of date
updating environment: [new config] 4 added, 0 changed, 0 removed
reading sources... [ 25%] 1                                                     
Exception occurred:
  File "/home/yt/projects/Experimental/ablog/ablog/post.py", line 40, in _split
    return {s.strip() for s in a.split(",")}
AttributeError: 'NoneType' object has no attribute 'split'
The full traceback has been saved in /run/user/1000/tmp.H5flR328yV/sphinx-err-_3o1p9bs.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### Expected behavior

It was fine before 0.10.27.
This behavior seems to be introduced with a3a8fb932dae00cd7766bd38554f98947104f37b.

### Screenshots

_No response_

### System Details

```
==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Thursday, 11. August 2022 11:20AM UT
System : Linux
Processor :
Arch : 64bit
SunPy : 2.0.7
OS: Debian GNU/Linux 11 bullseye (Linux 5.10.0-16-amd64 )


##################
Required Libraries
##################
Python: 3.9.2
NumPy: 1.19.5
SciPy: 1.6.0
matplotlib: 3.3.4
Astropy: 4.2
Pandas: 1.1.5
parfive: NOT INSTALLED


#####################
Recommended Libraries
#####################
beautifulsoup: NOT INSTALLED
PyQt4: NOT INSTALLED
PyQt5: 5.15.2
Zeep: NOT INSTALLED
Sqlalchemy: NOT INSTALLED
drms: NOT INSTALLED
```

### Installation method

pip

### PR DESCRIPTION
**Pull request by ytomino**
## PR Description

Fix #154

Restore `or ""` that is deleted in a3a8fb932dae00cd7766bd38554f98947104f37b.

### CODE REVIEW

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Thanks, I will merge this later today and get a release out.
